# Generated by Django 4.0.4 on 2022-07-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('idSucursal', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='idSucursal')),
                ('nombresucursal', models.CharField(max_length=30, verbose_name='NombreSucursal')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('horario', models.CharField(max_length=50, verbose_name='Horario')),
                ('festivos', models.CharField(max_length=50, verbose_name='Festivos')),
            ],
        ),
    ]
